title: "Iago Lastra"
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" 
url: https://iagolast.github.io 
twitter_username: iagolast
github_username:  iagolast
default_author: Iago Lastra
logo_url: https://pbs.twimg.com/profile_images/431818299291099136/Iia0gR8i_200x200.png
logo_w: 200
logo_h: 200
ga_account: UA-42054532-4
description: "IagoLast's personal site"

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
