title: "Iago Lastra"
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" 
url: https://iagolast.github.io 
twitter_username: iagolast
github_username:  iagolast

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
